version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
  build:
    commands:
      - aws sts get-caller-identity
      # Use AWS SAM to package the application using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      # mljsapi-itest-artifacts
      # - aws cloudformation package --template template.yml --s3-bucket mljsapi-itest-artifacts --output-template template-export-itest.yml
      # - echo "packaged template-export-itest.yml"
      - aws cloudformation deploy --template-file template-export.yml --stack-name mljsapi-itest
artifacts:
  type: zip
  files:
    - template-export.yml
