AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectId:
    Description: AWS CodeStar projectID used to associate new resources to team members
    Type: String
Resources:
  Assignments:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /assignments
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /assignments
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 60
    Type: AWS::Serverless::Function
  CloseSeder:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /close-seder
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /close-seder
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 40
    Type: AWS::Serverless::Function
  DB:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /db
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /db
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /db
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 10
    Type: AWS::Serverless::Function
  GetCookies:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /get-cookies
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /get-cookies
          Type: Api
      Handler: index.handler
      MemorySize: 1792
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 30
    Type: AWS::Serverless::Function
  HelloWorld:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /
          Type: Api
      Handler: index.handler
      Policies: AmazonDynamoDBFullAccess
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
    Type: AWS::Serverless::Function
  Id:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /id
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /id
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 30
    Type: AWS::Serverless::Function
  JoinSeder:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /join-seder
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /join-seder
          Type: Api
      Handler: index.handler
      MemorySize: 1792
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 30
    Type: AWS::Serverless::Function
  Play:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /play
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /play
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /play
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 5
    Type: AWS::Serverless::Function
  Playground:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /playground
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /playground
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 30
    Type: AWS::Serverless::Function
  PublicEndpoint:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /public-endpoint
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /public-endpoint
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 5
    Type: AWS::Serverless::Function
  ReadRoster:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /read-roster
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /read-roster
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 60
    Type: AWS::Serverless::Function
  RoomCode:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /room-code
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /room-code
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 40
    Type: AWS::Serverless::Function
  Roster:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /roster
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /roster
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 40
    Type: AWS::Serverless::Function
  Script:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /script
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /script
          Type: Api
      Handler: index.handler
      MemorySize: 1792
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 80
    Type: AWS::Serverless::Function
  Scripts:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /scripts
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /scripts
          Type: Api
      Handler: index.handler
      MemorySize: 1792
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 30
    Type: AWS::Serverless::Function
  SubmitLibs:
    Properties:
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /submit-libs
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /submit-libs
          Type: Api
      Handler: index.handler
      MemorySize: 3008
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs12.x
      Timeout: 40
    Type: AWS::Serverless::Function
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar
