AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectId:
    Description: AWS CodeStar projectID used to associate new resources to team members
    Type: String
Resources:
  DB:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /db
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /db
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  GetCookies:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /get-cookies
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /get-cookies
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  HelloWorld:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /
          Type: Api
      Handler: index.handler
      Policies: AmazonDynamoDBFullAccess
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  JoinSeder:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /join-seder
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /join-seder
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  Playground:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /playground
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /playground
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ProtectedEndpoint:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /protected-endpoint
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /protected-endpoint
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /protected-endpoint
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PublicEndpoint:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /public-endpoint
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /public-endpoint
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  RoomCode:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        OptionsEvent:
          Properties:
            Method: options
            Path: /room-code
          Type: Api
        PostEvent:
          Properties:
            Method: post
            Path: /room-code
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  Roster:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /roster
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /roster
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  Scripts:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /scripts
          Type: Api
        OptionsEvent:
          Properties:
            Method: options
            Path: /scripts
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar
