AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectId:
    Description: AWS CodeStar projectID used to associate new resources to team members
    Type: String
Resources:
  HelloWorld:
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: index.handler
      Role: !ImportValue
        Fn::Join:
          - '-'
          - - !Ref 'ProjectId'
            - !Ref 'AWS::Region'
            - LambdaTrustRole
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar
